# Generated by Django 5.2 on 2025-11-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description2',
            field=models.TextField(default='brak opisu'),
            preserve_default=False,
        ),
    ]
